### PR TITLE
Add support for 2022.2 EAP

### LINKED ISSUE #182: Support for 2022.2 EAP
IntelliJ started a new EAP for 2022.2.
Build number: #IU-222.2270.31

Could you make a build for the new version please?
Thank you! 😀

### PR DESCRIPTION
**Pull request by Masrepus**
Closes #182

### CODE REVIEW

**Comment by Kantis** [comment]
Looks like EAP sdkVersion should be specified a bit differently.. See https://github.com/kotest/kotest-intellij-plugin/commit/6500f92c4e3aa1919724bd306e2f74487503d2dc

**Comment by Masrepus** [comment]
Ahh that makes sense!

**Comment by sksamuel** [comment]
thanks!

**Comment by Masrepus** [comment]
@sksamuel would you mind running the release pipeline sometime soon so that we can update the plugin via Intellij? 😄

**Comment by sksamuel** [comment]
Done.

We have to wait for jb to approve it.

**Comment by sksamuel** [comment]
Looks like it failed. Will check over the pr when I get home.

**Comment by Masrepus** [comment]
Super weird, I didn't even touch any files related to 19.3 😅

**Pull request merged**
