### PR TITLE
Normalize multiline string spec test names.

### PR DESCRIPTION
**Pull request by canatella**
Currently, when defining a test in a `StringSpec` with multiple lines, it cannot be run by clicking the icon next to it. For example:
```
class MyTests : StringSpec({

    """This test name is spread
        over multiple lines withe indentation.
    """ {
        true shouldBe true
    }
})
```

The output when hitting the run single test icon:
```
... io.kotest.engine.launcher.MainKt --spec MyTests --testpath This test name is spread
        over multiple lines withe indentation.
     --reporter teamcity
Testing started at 10:51 ...

Process finished with exit code 0

This test name is spread over multiple lines withe indentation. is excluded by test filter(s): Excluded by test path filter: 'This test name is spread
        over multiple lines withe indentation.
    '

Replacing all consecutive white space in the name by a single space fixes the issue.

```
... io.kotest.engine.launcher.MainKt --spec com.bloomlife.lib.athena.MyTests --testpath This test name is spread over multiple lines withe indentation.  --reporter teamcity
Testing started at 10:54 ...

Process finished with exit code 0
```

### CODE REVIEW

**Comment by Kantis** [comment]
I believe this would solve #255 as well.. need to verify it.

**Comment by canatella** [comment]
Any news ?

**Comment by canatella** [comment]
That's not really nice. I take the time to submit a PR that fixes an issue. Nobody reacts, which I can understand, we are all busy, but then it's closed automatically. Come on...

**Comment by sksamuel** [comment]
Just the stale bot. Reopened.

**Comment by sksamuel** [comment]
@canatella if you build this locally and install it, can you confirm you can then run multi-line tests from intellij?

I think we need to check as well that if you have a test with double spaces deliberately, it still works, because you're matching on \s+ rather than \n say.

**Comment by canatella** [comment]
@sksamuel I'm trying to add a unit test, but it seems I can't run them. What is the proper way to run the tests ? I'm using
```
PRODUCT_NAME=IC-233 ./gradlew check -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" 
```
But I have 
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.intellij.testFramework.TestLoggerFactory$TestLoggerAssertionError: Index data initialization failed
```

**Comment by sksamuel** [comment]
That seems to be an issue with any of the 23x builds. I test locally against 22x.

**Pull request merged**
